
/*------------------------------------------------------------------------
    File        : LoggingLevels
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : claudiu.spac
    Created     : Fri Aug 30 15:39:37 EEST 2024
    Notes       : 
  ----------------------------------------------------------------------*/

enum Logger.LoggingLevels :  
define enum 
  debug
  info
  warning
  error.
end enum.